/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as IndexImport } from './routes/index'
import { Route as authSignInImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated/teacher/route'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/student/route'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminSectionsRouteImport } from './routes/_authenticated/admin/sections/route'
import { Route as AuthenticatedStudentQrScanIndexImport } from './routes/_authenticated/student/qr-scan/index'
import { Route as AuthenticatedStudentClassScheduleIndexImport } from './routes/_authenticated/student/class-schedule/index'
import { Route as AuthenticatedSettingsProfileIndexImport } from './routes/_authenticated/settings/profile/index'
import { Route as AuthenticatedSettingsPasswordIndexImport } from './routes/_authenticated/settings/password/index'
import { Route as AuthenticatedSettingsAppearanceIndexImport } from './routes/_authenticated/settings/appearance/index'
import { Route as AuthenticatedAdminUsersIndexImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminSubjectsIndexImport } from './routes/_authenticated/admin/subjects/index'
import { Route as AuthenticatedAdminCoursesIndexImport } from './routes/_authenticated/admin/courses/index'
import { Route as AuthenticatedTeacherClassScheduleScheduleIdRouteImport } from './routes/_authenticated/teacher/class-schedule/$scheduleId/route'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin/users/$userId/route'
import { Route as AuthenticatedTeacherClassScheduleScheduleIdIndexImport } from './routes/_authenticated/teacher/class-schedule/$scheduleId/index'
import { Route as AuthenticatedStudentClassScheduleScheduleIdIndexImport } from './routes/_authenticated/student/class-schedule/$scheduleId/index'
import { Route as AuthenticatedAdminUsersUserIdIndexImport } from './routes/_authenticated/admin/users/$userId/index'
import { Route as AuthenticatedAdminSectionsIdIndexImport } from './routes/_authenticated/admin/sections/$id/index'
import { Route as AuthenticatedAdminUsersUserIdGuardianImport } from './routes/_authenticated/admin/users/$userId/guardian'
import { Route as AuthenticatedAdminUsersUserIdClassScheduleImport } from './routes/_authenticated/admin/users/$userId/class-schedule'
import { Route as AuthenticatedStudentClassScheduleScheduleIdSessionSessionIdImport } from './routes/_authenticated/student/class-schedule/$scheduleId/session/$sessionId'

// Create Virtual Routes

const errors503LazyImport = createFileRoute('/(errors)/503')()
const errors500LazyImport = createFileRoute('/(errors)/500')()
const errors404LazyImport = createFileRoute('/(errors)/404')()
const errors403LazyImport = createFileRoute('/(errors)/403')()
const errors401LazyImport = createFileRoute('/(errors)/401')()
const authForgotPasswordLazyImport = createFileRoute(
  '/(auth)/forgot-password',
)()
const AuthenticatedSettingsRouteLazyImport = createFileRoute(
  '/_authenticated/settings',
)()
const AuthenticatedTeacherIndexLazyImport = createFileRoute(
  '/_authenticated/teacher/',
)()
const AuthenticatedStudentIndexLazyImport = createFileRoute(
  '/_authenticated/student/',
)()
const AuthenticatedComingSoonIndexLazyImport = createFileRoute(
  '/_authenticated/coming-soon/',
)()
const AuthenticatedTeacherClassScheduleIndexLazyImport = createFileRoute(
  '/_authenticated/teacher/class-schedule/',
)()
const AuthenticatedAdminSectionsIndexLazyImport = createFileRoute(
  '/_authenticated/admin/sections/',
)()
const AuthenticatedTeacherClassScheduleScheduleIdSessionSessionIdLazyImport =
  createFileRoute(
    '/_authenticated/teacher/class-schedule/$scheduleId/session/$sessionId',
  )()

// Create/Update Routes

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const errors503LazyRoute = errors503LazyImport
  .update({
    id: '/(errors)/503',
    path: '/503',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/503.lazy').then((d) => d.Route))

const errors500LazyRoute = errors500LazyImport
  .update({
    id: '/(errors)/500',
    path: '/500',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/500.lazy').then((d) => d.Route))

const errors404LazyRoute = errors404LazyImport
  .update({
    id: '/(errors)/404',
    path: '/404',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/404.lazy').then((d) => d.Route))

const errors403LazyRoute = errors403LazyImport
  .update({
    id: '/(errors)/403',
    path: '/403',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/403.lazy').then((d) => d.Route))

const errors401LazyRoute = errors401LazyImport
  .update({
    id: '/(errors)/401',
    path: '/401',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/401.lazy').then((d) => d.Route))

const authForgotPasswordLazyRoute = authForgotPasswordLazyImport
  .update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/forgot-password.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsRouteLazyRoute =
  AuthenticatedSettingsRouteLazyImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/route.lazy').then((d) => d.Route),
  )

const authSignInRoute = authSignInImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedTeacherRouteRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedStudentRouteRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedTeacherIndexLazyRoute =
  AuthenticatedTeacherIndexLazyImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/teacher/index.lazy').then((d) => d.Route),
  )

const AuthenticatedStudentIndexLazyRoute =
  AuthenticatedStudentIndexLazyImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/student/index.lazy').then((d) => d.Route),
  )

const AuthenticatedComingSoonIndexLazyRoute =
  AuthenticatedComingSoonIndexLazyImport.update({
    id: '/coming-soon/',
    path: '/coming-soon/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/coming-soon/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedAdminSectionsRouteRoute =
  AuthenticatedAdminSectionsRouteImport.update({
    id: '/sections',
    path: '/sections',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedTeacherClassScheduleIndexLazyRoute =
  AuthenticatedTeacherClassScheduleIndexLazyImport.update({
    id: '/class-schedule/',
    path: '/class-schedule/',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/teacher/class-schedule/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedAdminSectionsIndexLazyRoute =
  AuthenticatedAdminSectionsIndexLazyImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminSectionsRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/sections/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedStudentQrScanIndexRoute =
  AuthenticatedStudentQrScanIndexImport.update({
    id: '/qr-scan/',
    path: '/qr-scan/',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)

const AuthenticatedStudentClassScheduleIndexRoute =
  AuthenticatedStudentClassScheduleIndexImport.update({
    id: '/class-schedule/',
    path: '/class-schedule/',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)

const AuthenticatedSettingsProfileIndexRoute =
  AuthenticatedSettingsProfileIndexImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any)

const AuthenticatedSettingsPasswordIndexRoute =
  AuthenticatedSettingsPasswordIndexImport.update({
    id: '/password/',
    path: '/password/',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any)

const AuthenticatedSettingsAppearanceIndexRoute =
  AuthenticatedSettingsAppearanceIndexImport.update({
    id: '/appearance/',
    path: '/appearance/',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any)

const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminSubjectsIndexRoute =
  AuthenticatedAdminSubjectsIndexImport.update({
    id: '/subjects/',
    path: '/subjects/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedAdminCoursesIndexRoute =
  AuthenticatedAdminCoursesIndexImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedTeacherClassScheduleScheduleIdRouteRoute =
  AuthenticatedTeacherClassScheduleScheduleIdRouteImport.update({
    id: '/class-schedule/$scheduleId',
    path: '/class-schedule/$scheduleId',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)

const AuthenticatedAdminUsersUserIdRouteRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

const AuthenticatedTeacherClassScheduleScheduleIdIndexRoute =
  AuthenticatedTeacherClassScheduleScheduleIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTeacherClassScheduleScheduleIdRouteRoute,
  } as any)

const AuthenticatedStudentClassScheduleScheduleIdIndexRoute =
  AuthenticatedStudentClassScheduleScheduleIdIndexImport.update({
    id: '/class-schedule/$scheduleId/',
    path: '/class-schedule/$scheduleId/',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)

const AuthenticatedAdminUsersUserIdIndexRoute =
  AuthenticatedAdminUsersUserIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminUsersUserIdRouteRoute,
  } as any)

const AuthenticatedAdminSectionsIdIndexRoute =
  AuthenticatedAdminSectionsIdIndexImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => AuthenticatedAdminSectionsRouteRoute,
  } as any)

const AuthenticatedAdminUsersUserIdGuardianRoute =
  AuthenticatedAdminUsersUserIdGuardianImport.update({
    id: '/guardian',
    path: '/guardian',
    getParentRoute: () => AuthenticatedAdminUsersUserIdRouteRoute,
  } as any)

const AuthenticatedAdminUsersUserIdClassScheduleRoute =
  AuthenticatedAdminUsersUserIdClassScheduleImport.update({
    id: '/class-schedule',
    path: '/class-schedule',
    getParentRoute: () => AuthenticatedAdminUsersUserIdRouteRoute,
  } as any)

const AuthenticatedTeacherClassScheduleScheduleIdSessionSessionIdLazyRoute =
  AuthenticatedTeacherClassScheduleScheduleIdSessionSessionIdLazyImport.update({
    id: '/session/$sessionId',
    path: '/session/$sessionId',
    getParentRoute: () => AuthenticatedTeacherClassScheduleScheduleIdRouteRoute,
  } as any).lazy(() =>
    import(
      './routes/_authenticated/teacher/class-schedule/$scheduleId/session/$sessionId.lazy'
    ).then((d) => d.Route),
  )

const AuthenticatedStudentClassScheduleScheduleIdSessionSessionIdRoute =
  AuthenticatedStudentClassScheduleScheduleIdSessionSessionIdImport.update({
    id: '/class-schedule/$scheduleId/session/$sessionId',
    path: '/class-schedule/$scheduleId/session/$sessionId',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503LazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/admin/sections': {
      id: '/_authenticated/admin/sections'
      path: '/sections'
      fullPath: '/admin/sections'
      preLoaderRoute: typeof AuthenticatedAdminSectionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/coming-soon/': {
      id: '/_authenticated/coming-soon/'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof AuthenticatedComingSoonIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthenticatedStudentIndexLazyImport
      parentRoute: typeof AuthenticatedStudentRouteImport
    }
    '/_authenticated/teacher/': {
      id: '/_authenticated/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AuthenticatedTeacherIndexLazyImport
      parentRoute: typeof AuthenticatedTeacherRouteImport
    }
    '/_authenticated/admin/users/$userId': {
      id: '/_authenticated/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/teacher/class-schedule/$scheduleId': {
      id: '/_authenticated/teacher/class-schedule/$scheduleId'
      path: '/class-schedule/$scheduleId'
      fullPath: '/teacher/class-schedule/$scheduleId'
      preLoaderRoute: typeof AuthenticatedTeacherClassScheduleScheduleIdRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteImport
    }
    '/_authenticated/admin/courses/': {
      id: '/_authenticated/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesIndexImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/subjects/': {
      id: '/_authenticated/admin/subjects/'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AuthenticatedAdminSubjectsIndexImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/settings/appearance/': {
      id: '/_authenticated/settings/appearance/'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceIndexImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/password/': {
      id: '/_authenticated/settings/password/'
      path: '/password'
      fullPath: '/settings/password'
      preLoaderRoute: typeof AuthenticatedSettingsPasswordIndexImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/profile/': {
      id: '/_authenticated/settings/profile/'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileIndexImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/student/class-schedule/': {
      id: '/_authenticated/student/class-schedule/'
      path: '/class-schedule'
      fullPath: '/student/class-schedule'
      preLoaderRoute: typeof AuthenticatedStudentClassScheduleIndexImport
      parentRoute: typeof AuthenticatedStudentRouteImport
    }
    '/_authenticated/student/qr-scan/': {
      id: '/_authenticated/student/qr-scan/'
      path: '/qr-scan'
      fullPath: '/student/qr-scan'
      preLoaderRoute: typeof AuthenticatedStudentQrScanIndexImport
      parentRoute: typeof AuthenticatedStudentRouteImport
    }
    '/_authenticated/admin/sections/': {
      id: '/_authenticated/admin/sections/'
      path: '/'
      fullPath: '/admin/sections/'
      preLoaderRoute: typeof AuthenticatedAdminSectionsIndexLazyImport
      parentRoute: typeof AuthenticatedAdminSectionsRouteImport
    }
    '/_authenticated/teacher/class-schedule/': {
      id: '/_authenticated/teacher/class-schedule/'
      path: '/class-schedule'
      fullPath: '/teacher/class-schedule'
      preLoaderRoute: typeof AuthenticatedTeacherClassScheduleIndexLazyImport
      parentRoute: typeof AuthenticatedTeacherRouteImport
    }
    '/_authenticated/admin/users/$userId/class-schedule': {
      id: '/_authenticated/admin/users/$userId/class-schedule'
      path: '/class-schedule'
      fullPath: '/admin/users/$userId/class-schedule'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdClassScheduleImport
      parentRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
    }
    '/_authenticated/admin/users/$userId/guardian': {
      id: '/_authenticated/admin/users/$userId/guardian'
      path: '/guardian'
      fullPath: '/admin/users/$userId/guardian'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdGuardianImport
      parentRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
    }
    '/_authenticated/admin/sections/$id/': {
      id: '/_authenticated/admin/sections/$id/'
      path: '/$id'
      fullPath: '/admin/sections/$id'
      preLoaderRoute: typeof AuthenticatedAdminSectionsIdIndexImport
      parentRoute: typeof AuthenticatedAdminSectionsRouteImport
    }
    '/_authenticated/admin/users/$userId/': {
      id: '/_authenticated/admin/users/$userId/'
      path: '/'
      fullPath: '/admin/users/$userId/'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdIndexImport
      parentRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
    }
    '/_authenticated/student/class-schedule/$scheduleId/': {
      id: '/_authenticated/student/class-schedule/$scheduleId/'
      path: '/class-schedule/$scheduleId'
      fullPath: '/student/class-schedule/$scheduleId'
      preLoaderRoute: typeof AuthenticatedStudentClassScheduleScheduleIdIndexImport
      parentRoute: typeof AuthenticatedStudentRouteImport
    }
    '/_authenticated/teacher/class-schedule/$scheduleId/': {
      id: '/_authenticated/teacher/class-schedule/$scheduleId/'
      path: '/'
      fullPath: '/teacher/class-schedule/$scheduleId/'
      preLoaderRoute: typeof AuthenticatedTeacherClassScheduleScheduleIdIndexImport
      parentRoute: typeof AuthenticatedTeacherClassScheduleScheduleIdRouteImport
    }
    '/_authenticated/student/class-schedule/$scheduleId/session/$sessionId': {
      id: '/_authenticated/student/class-schedule/$scheduleId/session/$sessionId'
      path: '/class-schedule/$scheduleId/session/$sessionId'
      fullPath: '/student/class-schedule/$scheduleId/session/$sessionId'
      preLoaderRoute: typeof AuthenticatedStudentClassScheduleScheduleIdSessionSessionIdImport
      parentRoute: typeof AuthenticatedStudentRouteImport
    }
    '/_authenticated/teacher/class-schedule/$scheduleId/session/$sessionId': {
      id: '/_authenticated/teacher/class-schedule/$scheduleId/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/teacher/class-schedule/$scheduleId/session/$sessionId'
      preLoaderRoute: typeof AuthenticatedTeacherClassScheduleScheduleIdSessionSessionIdLazyImport
      parentRoute: typeof AuthenticatedTeacherClassScheduleScheduleIdRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedAdminSectionsRouteRouteChildren {
  AuthenticatedAdminSectionsIndexLazyRoute: typeof AuthenticatedAdminSectionsIndexLazyRoute
  AuthenticatedAdminSectionsIdIndexRoute: typeof AuthenticatedAdminSectionsIdIndexRoute
}

const AuthenticatedAdminSectionsRouteRouteChildren: AuthenticatedAdminSectionsRouteRouteChildren =
  {
    AuthenticatedAdminSectionsIndexLazyRoute:
      AuthenticatedAdminSectionsIndexLazyRoute,
    AuthenticatedAdminSectionsIdIndexRoute:
      AuthenticatedAdminSectionsIdIndexRoute,
  }

const AuthenticatedAdminSectionsRouteRouteWithChildren =
  AuthenticatedAdminSectionsRouteRoute._addFileChildren(
    AuthenticatedAdminSectionsRouteRouteChildren,
  )

interface AuthenticatedAdminUsersUserIdRouteRouteChildren {
  AuthenticatedAdminUsersUserIdClassScheduleRoute: typeof AuthenticatedAdminUsersUserIdClassScheduleRoute
  AuthenticatedAdminUsersUserIdGuardianRoute: typeof AuthenticatedAdminUsersUserIdGuardianRoute
  AuthenticatedAdminUsersUserIdIndexRoute: typeof AuthenticatedAdminUsersUserIdIndexRoute
}

const AuthenticatedAdminUsersUserIdRouteRouteChildren: AuthenticatedAdminUsersUserIdRouteRouteChildren =
  {
    AuthenticatedAdminUsersUserIdClassScheduleRoute:
      AuthenticatedAdminUsersUserIdClassScheduleRoute,
    AuthenticatedAdminUsersUserIdGuardianRoute:
      AuthenticatedAdminUsersUserIdGuardianRoute,
    AuthenticatedAdminUsersUserIdIndexRoute:
      AuthenticatedAdminUsersUserIdIndexRoute,
  }

const AuthenticatedAdminUsersUserIdRouteRouteWithChildren =
  AuthenticatedAdminUsersUserIdRouteRoute._addFileChildren(
    AuthenticatedAdminUsersUserIdRouteRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminSectionsRouteRoute: typeof AuthenticatedAdminSectionsRouteRouteWithChildren
  AuthenticatedAdminUsersUserIdRouteRoute: typeof AuthenticatedAdminUsersUserIdRouteRouteWithChildren
  AuthenticatedAdminCoursesIndexRoute: typeof AuthenticatedAdminCoursesIndexRoute
  AuthenticatedAdminSubjectsIndexRoute: typeof AuthenticatedAdminSubjectsIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminSectionsRouteRoute:
      AuthenticatedAdminSectionsRouteRouteWithChildren,
    AuthenticatedAdminUsersUserIdRouteRoute:
      AuthenticatedAdminUsersUserIdRouteRouteWithChildren,
    AuthenticatedAdminCoursesIndexRoute: AuthenticatedAdminCoursesIndexRoute,
    AuthenticatedAdminSubjectsIndexRoute: AuthenticatedAdminSubjectsIndexRoute,
    AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedStudentRouteRouteChildren {
  AuthenticatedStudentIndexLazyRoute: typeof AuthenticatedStudentIndexLazyRoute
  AuthenticatedStudentClassScheduleIndexRoute: typeof AuthenticatedStudentClassScheduleIndexRoute
  AuthenticatedStudentQrScanIndexRoute: typeof AuthenticatedStudentQrScanIndexRoute
  AuthenticatedStudentClassScheduleScheduleIdIndexRoute: typeof AuthenticatedStudentClassScheduleScheduleIdIndexRoute
  AuthenticatedStudentClassScheduleScheduleIdSessionSessionIdRoute: typeof AuthenticatedStudentClassScheduleScheduleIdSessionSessionIdRoute
}

const AuthenticatedStudentRouteRouteChildren: AuthenticatedStudentRouteRouteChildren =
  {
    AuthenticatedStudentIndexLazyRoute: AuthenticatedStudentIndexLazyRoute,
    AuthenticatedStudentClassScheduleIndexRoute:
      AuthenticatedStudentClassScheduleIndexRoute,
    AuthenticatedStudentQrScanIndexRoute: AuthenticatedStudentQrScanIndexRoute,
    AuthenticatedStudentClassScheduleScheduleIdIndexRoute:
      AuthenticatedStudentClassScheduleScheduleIdIndexRoute,
    AuthenticatedStudentClassScheduleScheduleIdSessionSessionIdRoute:
      AuthenticatedStudentClassScheduleScheduleIdSessionSessionIdRoute,
  }

const AuthenticatedStudentRouteRouteWithChildren =
  AuthenticatedStudentRouteRoute._addFileChildren(
    AuthenticatedStudentRouteRouteChildren,
  )

interface AuthenticatedTeacherClassScheduleScheduleIdRouteRouteChildren {
  AuthenticatedTeacherClassScheduleScheduleIdIndexRoute: typeof AuthenticatedTeacherClassScheduleScheduleIdIndexRoute
  AuthenticatedTeacherClassScheduleScheduleIdSessionSessionIdLazyRoute: typeof AuthenticatedTeacherClassScheduleScheduleIdSessionSessionIdLazyRoute
}

const AuthenticatedTeacherClassScheduleScheduleIdRouteRouteChildren: AuthenticatedTeacherClassScheduleScheduleIdRouteRouteChildren =
  {
    AuthenticatedTeacherClassScheduleScheduleIdIndexRoute:
      AuthenticatedTeacherClassScheduleScheduleIdIndexRoute,
    AuthenticatedTeacherClassScheduleScheduleIdSessionSessionIdLazyRoute:
      AuthenticatedTeacherClassScheduleScheduleIdSessionSessionIdLazyRoute,
  }

const AuthenticatedTeacherClassScheduleScheduleIdRouteRouteWithChildren =
  AuthenticatedTeacherClassScheduleScheduleIdRouteRoute._addFileChildren(
    AuthenticatedTeacherClassScheduleScheduleIdRouteRouteChildren,
  )

interface AuthenticatedTeacherRouteRouteChildren {
  AuthenticatedTeacherIndexLazyRoute: typeof AuthenticatedTeacherIndexLazyRoute
  AuthenticatedTeacherClassScheduleScheduleIdRouteRoute: typeof AuthenticatedTeacherClassScheduleScheduleIdRouteRouteWithChildren
  AuthenticatedTeacherClassScheduleIndexLazyRoute: typeof AuthenticatedTeacherClassScheduleIndexLazyRoute
}

const AuthenticatedTeacherRouteRouteChildren: AuthenticatedTeacherRouteRouteChildren =
  {
    AuthenticatedTeacherIndexLazyRoute: AuthenticatedTeacherIndexLazyRoute,
    AuthenticatedTeacherClassScheduleScheduleIdRouteRoute:
      AuthenticatedTeacherClassScheduleScheduleIdRouteRouteWithChildren,
    AuthenticatedTeacherClassScheduleIndexLazyRoute:
      AuthenticatedTeacherClassScheduleIndexLazyRoute,
  }

const AuthenticatedTeacherRouteRouteWithChildren =
  AuthenticatedTeacherRouteRoute._addFileChildren(
    AuthenticatedTeacherRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteLazyRouteChildren {
  AuthenticatedSettingsAppearanceIndexRoute: typeof AuthenticatedSettingsAppearanceIndexRoute
  AuthenticatedSettingsPasswordIndexRoute: typeof AuthenticatedSettingsPasswordIndexRoute
  AuthenticatedSettingsProfileIndexRoute: typeof AuthenticatedSettingsProfileIndexRoute
}

const AuthenticatedSettingsRouteLazyRouteChildren: AuthenticatedSettingsRouteLazyRouteChildren =
  {
    AuthenticatedSettingsAppearanceIndexRoute:
      AuthenticatedSettingsAppearanceIndexRoute,
    AuthenticatedSettingsPasswordIndexRoute:
      AuthenticatedSettingsPasswordIndexRoute,
    AuthenticatedSettingsProfileIndexRoute:
      AuthenticatedSettingsProfileIndexRoute,
  }

const AuthenticatedSettingsRouteLazyRouteWithChildren =
  AuthenticatedSettingsRouteLazyRoute._addFileChildren(
    AuthenticatedSettingsRouteLazyRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedStudentRouteRoute: typeof AuthenticatedStudentRouteRouteWithChildren
  AuthenticatedTeacherRouteRoute: typeof AuthenticatedTeacherRouteRouteWithChildren
  AuthenticatedSettingsRouteLazyRoute: typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  AuthenticatedComingSoonIndexLazyRoute: typeof AuthenticatedComingSoonIndexLazyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedStudentRouteRoute: AuthenticatedStudentRouteRouteWithChildren,
  AuthenticatedTeacherRouteRoute: AuthenticatedTeacherRouteRouteWithChildren,
  AuthenticatedSettingsRouteLazyRoute:
    AuthenticatedSettingsRouteLazyRouteWithChildren,
  AuthenticatedComingSoonIndexLazyRoute: AuthenticatedComingSoonIndexLazyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/student': typeof AuthenticatedStudentRouteRouteWithChildren
  '/teacher': typeof AuthenticatedTeacherRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/500': typeof errors500LazyRoute
  '/503': typeof errors503LazyRoute
  '/admin/sections': typeof AuthenticatedAdminSectionsRouteRouteWithChildren
  '/coming-soon': typeof AuthenticatedComingSoonIndexLazyRoute
  '/student/': typeof AuthenticatedStudentIndexLazyRoute
  '/teacher/': typeof AuthenticatedTeacherIndexLazyRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRouteRouteWithChildren
  '/teacher/class-schedule/$scheduleId': typeof AuthenticatedTeacherClassScheduleScheduleIdRouteRouteWithChildren
  '/admin/courses': typeof AuthenticatedAdminCoursesIndexRoute
  '/admin/subjects': typeof AuthenticatedAdminSubjectsIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceIndexRoute
  '/settings/password': typeof AuthenticatedSettingsPasswordIndexRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileIndexRoute
  '/student/class-schedule': typeof AuthenticatedStudentClassScheduleIndexRoute
  '/student/qr-scan': typeof AuthenticatedStudentQrScanIndexRoute
  '/admin/sections/': typeof AuthenticatedAdminSectionsIndexLazyRoute
  '/teacher/class-schedule': typeof AuthenticatedTeacherClassScheduleIndexLazyRoute
  '/admin/users/$userId/class-schedule': typeof AuthenticatedAdminUsersUserIdClassScheduleRoute
  '/admin/users/$userId/guardian': typeof AuthenticatedAdminUsersUserIdGuardianRoute
  '/admin/sections/$id': typeof AuthenticatedAdminSectionsIdIndexRoute
  '/admin/users/$userId/': typeof AuthenticatedAdminUsersUserIdIndexRoute
  '/student/class-schedule/$scheduleId': typeof AuthenticatedStudentClassScheduleScheduleIdIndexRoute
  '/teacher/class-schedule/$scheduleId/': typeof AuthenticatedTeacherClassScheduleScheduleIdIndexRoute
  '/student/class-schedule/$scheduleId/session/$sessionId': typeof AuthenticatedStudentClassScheduleScheduleIdSessionSessionIdRoute
  '/teacher/class-schedule/$scheduleId/session/$sessionId': typeof AuthenticatedTeacherClassScheduleScheduleIdSessionSessionIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/500': typeof errors500LazyRoute
  '/503': typeof errors503LazyRoute
  '/coming-soon': typeof AuthenticatedComingSoonIndexLazyRoute
  '/student': typeof AuthenticatedStudentIndexLazyRoute
  '/teacher': typeof AuthenticatedTeacherIndexLazyRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesIndexRoute
  '/admin/subjects': typeof AuthenticatedAdminSubjectsIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceIndexRoute
  '/settings/password': typeof AuthenticatedSettingsPasswordIndexRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileIndexRoute
  '/student/class-schedule': typeof AuthenticatedStudentClassScheduleIndexRoute
  '/student/qr-scan': typeof AuthenticatedStudentQrScanIndexRoute
  '/admin/sections': typeof AuthenticatedAdminSectionsIndexLazyRoute
  '/teacher/class-schedule': typeof AuthenticatedTeacherClassScheduleIndexLazyRoute
  '/admin/users/$userId/class-schedule': typeof AuthenticatedAdminUsersUserIdClassScheduleRoute
  '/admin/users/$userId/guardian': typeof AuthenticatedAdminUsersUserIdGuardianRoute
  '/admin/sections/$id': typeof AuthenticatedAdminSectionsIdIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdIndexRoute
  '/student/class-schedule/$scheduleId': typeof AuthenticatedStudentClassScheduleScheduleIdIndexRoute
  '/teacher/class-schedule/$scheduleId': typeof AuthenticatedTeacherClassScheduleScheduleIdIndexRoute
  '/student/class-schedule/$scheduleId/session/$sessionId': typeof AuthenticatedStudentClassScheduleScheduleIdSessionSessionIdRoute
  '/teacher/class-schedule/$scheduleId/session/$sessionId': typeof AuthenticatedTeacherClassScheduleScheduleIdSessionSessionIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/student': typeof AuthenticatedStudentRouteRouteWithChildren
  '/_authenticated/teacher': typeof AuthenticatedTeacherRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordLazyRoute
  '/(errors)/401': typeof errors401LazyRoute
  '/(errors)/403': typeof errors403LazyRoute
  '/(errors)/404': typeof errors404LazyRoute
  '/(errors)/500': typeof errors500LazyRoute
  '/(errors)/503': typeof errors503LazyRoute
  '/_authenticated/admin/sections': typeof AuthenticatedAdminSectionsRouteRouteWithChildren
  '/_authenticated/coming-soon/': typeof AuthenticatedComingSoonIndexLazyRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexLazyRoute
  '/_authenticated/teacher/': typeof AuthenticatedTeacherIndexLazyRoute
  '/_authenticated/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRouteRouteWithChildren
  '/_authenticated/teacher/class-schedule/$scheduleId': typeof AuthenticatedTeacherClassScheduleScheduleIdRouteRouteWithChildren
  '/_authenticated/admin/courses/': typeof AuthenticatedAdminCoursesIndexRoute
  '/_authenticated/admin/subjects/': typeof AuthenticatedAdminSubjectsIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/settings/appearance/': typeof AuthenticatedSettingsAppearanceIndexRoute
  '/_authenticated/settings/password/': typeof AuthenticatedSettingsPasswordIndexRoute
  '/_authenticated/settings/profile/': typeof AuthenticatedSettingsProfileIndexRoute
  '/_authenticated/student/class-schedule/': typeof AuthenticatedStudentClassScheduleIndexRoute
  '/_authenticated/student/qr-scan/': typeof AuthenticatedStudentQrScanIndexRoute
  '/_authenticated/admin/sections/': typeof AuthenticatedAdminSectionsIndexLazyRoute
  '/_authenticated/teacher/class-schedule/': typeof AuthenticatedTeacherClassScheduleIndexLazyRoute
  '/_authenticated/admin/users/$userId/class-schedule': typeof AuthenticatedAdminUsersUserIdClassScheduleRoute
  '/_authenticated/admin/users/$userId/guardian': typeof AuthenticatedAdminUsersUserIdGuardianRoute
  '/_authenticated/admin/sections/$id/': typeof AuthenticatedAdminSectionsIdIndexRoute
  '/_authenticated/admin/users/$userId/': typeof AuthenticatedAdminUsersUserIdIndexRoute
  '/_authenticated/student/class-schedule/$scheduleId/': typeof AuthenticatedStudentClassScheduleScheduleIdIndexRoute
  '/_authenticated/teacher/class-schedule/$scheduleId/': typeof AuthenticatedTeacherClassScheduleScheduleIdIndexRoute
  '/_authenticated/student/class-schedule/$scheduleId/session/$sessionId': typeof AuthenticatedStudentClassScheduleScheduleIdSessionSessionIdRoute
  '/_authenticated/teacher/class-schedule/$scheduleId/session/$sessionId': typeof AuthenticatedTeacherClassScheduleScheduleIdSessionSessionIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/admin'
    | '/student'
    | '/teacher'
    | '/sign-in'
    | '/settings'
    | '/forgot-password'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/admin/sections'
    | '/coming-soon'
    | '/student/'
    | '/teacher/'
    | '/admin/users/$userId'
    | '/teacher/class-schedule/$scheduleId'
    | '/admin/courses'
    | '/admin/subjects'
    | '/admin/users'
    | '/settings/appearance'
    | '/settings/password'
    | '/settings/profile'
    | '/student/class-schedule'
    | '/student/qr-scan'
    | '/admin/sections/'
    | '/teacher/class-schedule'
    | '/admin/users/$userId/class-schedule'
    | '/admin/users/$userId/guardian'
    | '/admin/sections/$id'
    | '/admin/users/$userId/'
    | '/student/class-schedule/$scheduleId'
    | '/teacher/class-schedule/$scheduleId/'
    | '/student/class-schedule/$scheduleId/session/$sessionId'
    | '/teacher/class-schedule/$scheduleId/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/admin'
    | '/sign-in'
    | '/settings'
    | '/forgot-password'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/coming-soon'
    | '/student'
    | '/teacher'
    | '/admin/courses'
    | '/admin/subjects'
    | '/admin/users'
    | '/settings/appearance'
    | '/settings/password'
    | '/settings/profile'
    | '/student/class-schedule'
    | '/student/qr-scan'
    | '/admin/sections'
    | '/teacher/class-schedule'
    | '/admin/users/$userId/class-schedule'
    | '/admin/users/$userId/guardian'
    | '/admin/sections/$id'
    | '/admin/users/$userId'
    | '/student/class-schedule/$scheduleId'
    | '/teacher/class-schedule/$scheduleId'
    | '/student/class-schedule/$scheduleId/session/$sessionId'
    | '/teacher/class-schedule/$scheduleId/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/student'
    | '/_authenticated/teacher'
    | '/(auth)/sign-in'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/admin/sections'
    | '/_authenticated/coming-soon/'
    | '/_authenticated/student/'
    | '/_authenticated/teacher/'
    | '/_authenticated/admin/users/$userId'
    | '/_authenticated/teacher/class-schedule/$scheduleId'
    | '/_authenticated/admin/courses/'
    | '/_authenticated/admin/subjects/'
    | '/_authenticated/admin/users/'
    | '/_authenticated/settings/appearance/'
    | '/_authenticated/settings/password/'
    | '/_authenticated/settings/profile/'
    | '/_authenticated/student/class-schedule/'
    | '/_authenticated/student/qr-scan/'
    | '/_authenticated/admin/sections/'
    | '/_authenticated/teacher/class-schedule/'
    | '/_authenticated/admin/users/$userId/class-schedule'
    | '/_authenticated/admin/users/$userId/guardian'
    | '/_authenticated/admin/sections/$id/'
    | '/_authenticated/admin/users/$userId/'
    | '/_authenticated/student/class-schedule/$scheduleId/'
    | '/_authenticated/teacher/class-schedule/$scheduleId/'
    | '/_authenticated/student/class-schedule/$scheduleId/session/$sessionId'
    | '/_authenticated/teacher/class-schedule/$scheduleId/session/$sessionId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  authForgotPasswordLazyRoute: typeof authForgotPasswordLazyRoute
  errors401LazyRoute: typeof errors401LazyRoute
  errors403LazyRoute: typeof errors403LazyRoute
  errors404LazyRoute: typeof errors404LazyRoute
  errors500LazyRoute: typeof errors500LazyRoute
  errors503LazyRoute: typeof errors503LazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  authForgotPasswordLazyRoute: authForgotPasswordLazyRoute,
  errors401LazyRoute: errors401LazyRoute,
  errors403LazyRoute: errors403LazyRoute,
  errors404LazyRoute: errors404LazyRoute,
  errors500LazyRoute: errors500LazyRoute,
  errors503LazyRoute: errors503LazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/(auth)/sign-in",
        "/(auth)/forgot-password",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/(errors)/503"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/admin",
        "/_authenticated/student",
        "/_authenticated/teacher",
        "/_authenticated/settings",
        "/_authenticated/coming-soon/"
      ]
    },
    "/_authenticated/admin": {
      "filePath": "_authenticated/admin/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/admin/sections",
        "/_authenticated/admin/users/$userId",
        "/_authenticated/admin/courses/",
        "/_authenticated/admin/subjects/",
        "/_authenticated/admin/users/"
      ]
    },
    "/_authenticated/student": {
      "filePath": "_authenticated/student/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/student/",
        "/_authenticated/student/class-schedule/",
        "/_authenticated/student/qr-scan/",
        "/_authenticated/student/class-schedule/$scheduleId/",
        "/_authenticated/student/class-schedule/$scheduleId/session/$sessionId"
      ]
    },
    "/_authenticated/teacher": {
      "filePath": "_authenticated/teacher/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/teacher/",
        "/_authenticated/teacher/class-schedule/$scheduleId",
        "/_authenticated/teacher/class-schedule/"
      ]
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx"
    },
    "/_authenticated/settings": {
      "filePath": "_authenticated/settings/route.lazy.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/appearance/",
        "/_authenticated/settings/password/",
        "/_authenticated/settings/profile/"
      ]
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.lazy.tsx"
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.lazy.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.lazy.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.lazy.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.lazy.tsx"
    },
    "/(errors)/503": {
      "filePath": "(errors)/503.lazy.tsx"
    },
    "/_authenticated/admin/sections": {
      "filePath": "_authenticated/admin/sections/route.tsx",
      "parent": "/_authenticated/admin",
      "children": [
        "/_authenticated/admin/sections/",
        "/_authenticated/admin/sections/$id/"
      ]
    },
    "/_authenticated/coming-soon/": {
      "filePath": "_authenticated/coming-soon/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/student/": {
      "filePath": "_authenticated/student/index.lazy.tsx",
      "parent": "/_authenticated/student"
    },
    "/_authenticated/teacher/": {
      "filePath": "_authenticated/teacher/index.lazy.tsx",
      "parent": "/_authenticated/teacher"
    },
    "/_authenticated/admin/users/$userId": {
      "filePath": "_authenticated/admin/users/$userId/route.tsx",
      "parent": "/_authenticated/admin",
      "children": [
        "/_authenticated/admin/users/$userId/class-schedule",
        "/_authenticated/admin/users/$userId/guardian",
        "/_authenticated/admin/users/$userId/"
      ]
    },
    "/_authenticated/teacher/class-schedule/$scheduleId": {
      "filePath": "_authenticated/teacher/class-schedule/$scheduleId/route.tsx",
      "parent": "/_authenticated/teacher",
      "children": [
        "/_authenticated/teacher/class-schedule/$scheduleId/",
        "/_authenticated/teacher/class-schedule/$scheduleId/session/$sessionId"
      ]
    },
    "/_authenticated/admin/courses/": {
      "filePath": "_authenticated/admin/courses/index.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/subjects/": {
      "filePath": "_authenticated/admin/subjects/index.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/users/": {
      "filePath": "_authenticated/admin/users/index.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/settings/appearance/": {
      "filePath": "_authenticated/settings/appearance/index.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/password/": {
      "filePath": "_authenticated/settings/password/index.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/profile/": {
      "filePath": "_authenticated/settings/profile/index.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/student/class-schedule/": {
      "filePath": "_authenticated/student/class-schedule/index.tsx",
      "parent": "/_authenticated/student"
    },
    "/_authenticated/student/qr-scan/": {
      "filePath": "_authenticated/student/qr-scan/index.tsx",
      "parent": "/_authenticated/student"
    },
    "/_authenticated/admin/sections/": {
      "filePath": "_authenticated/admin/sections/index.lazy.tsx",
      "parent": "/_authenticated/admin/sections"
    },
    "/_authenticated/teacher/class-schedule/": {
      "filePath": "_authenticated/teacher/class-schedule/index.lazy.tsx",
      "parent": "/_authenticated/teacher"
    },
    "/_authenticated/admin/users/$userId/class-schedule": {
      "filePath": "_authenticated/admin/users/$userId/class-schedule.tsx",
      "parent": "/_authenticated/admin/users/$userId"
    },
    "/_authenticated/admin/users/$userId/guardian": {
      "filePath": "_authenticated/admin/users/$userId/guardian.tsx",
      "parent": "/_authenticated/admin/users/$userId"
    },
    "/_authenticated/admin/sections/$id/": {
      "filePath": "_authenticated/admin/sections/$id/index.tsx",
      "parent": "/_authenticated/admin/sections"
    },
    "/_authenticated/admin/users/$userId/": {
      "filePath": "_authenticated/admin/users/$userId/index.tsx",
      "parent": "/_authenticated/admin/users/$userId"
    },
    "/_authenticated/student/class-schedule/$scheduleId/": {
      "filePath": "_authenticated/student/class-schedule/$scheduleId/index.tsx",
      "parent": "/_authenticated/student"
    },
    "/_authenticated/teacher/class-schedule/$scheduleId/": {
      "filePath": "_authenticated/teacher/class-schedule/$scheduleId/index.tsx",
      "parent": "/_authenticated/teacher/class-schedule/$scheduleId"
    },
    "/_authenticated/student/class-schedule/$scheduleId/session/$sessionId": {
      "filePath": "_authenticated/student/class-schedule/$scheduleId/session/$sessionId.tsx",
      "parent": "/_authenticated/student"
    },
    "/_authenticated/teacher/class-schedule/$scheduleId/session/$sessionId": {
      "filePath": "_authenticated/teacher/class-schedule/$scheduleId/session/$sessionId.lazy.tsx",
      "parent": "/_authenticated/teacher/class-schedule/$scheduleId"
    }
  }
}
ROUTE_MANIFEST_END */
